version: '1.0'
stages:
  - 'clone'
  - 'build'
  # - "integration"
  - 'push'
steps:
  main_clone:
    type: 'git-clone'
    description: 'Cloning main repository...'
    repo: 'pehtoorismies/dt65-events-api'
    revision: '${{CF_BRANCH}}'
    stage: 'clone'
  build:
    title: 'Building Docker Image'
    type: 'build'
    image_name: 'pehtoorismies/dt65-events-api'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: 'Dockerfile'
    stage: 'build'
    disable_push: true
  push:
    title: 'Pushing image to dockerhub'
    type: 'push'
    registry: 'dockerhub'
    image_name: 'pehtoorismies/dt65-events-api'
    candidate: '${{build}}'
    tags:
      - '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    stage: 'push'
